// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangePermissions(arg1:string,arg2:number):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function StartTerminal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadFile(arg1:string):Promise<string>;

export function WriteFileContent(arg1:string,arg2:string):Promise<void>;

export function WriteToTerminal(arg1:string):Promise<void>;
