// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePermissions(arg1, arg2) {
  return window['go']['main']['App']['ChangePermissions'](arg1, arg2);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function StartTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3, arg4);
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}

export function WriteFileContent(arg1, arg2) {
  return window['go']['main']['App']['WriteFileContent'](arg1, arg2);
}

export function WriteToTerminal(arg1) {
  return window['go']['main']['App']['WriteToTerminal'](arg1);
}
